#include "arduino_secrets.h"
// Arduino_LSM6DS3 - Version: Latest 
#include <Arduino_LSM6DS3.h>

/* 
  Sketch generated by the Arduino IoT Cloud Thing "GyroscopeThing"
  https://create.arduino.cc/cloud/things/12e6a0e8-fd46-498a-aef6-2e1c17e8757e 

  Arduino IoT Cloud Properties description

  The following variables are automatically generated and updated when changes are made to the Thing properties

  float xDegree;
  float yDegree;
  float zDegree;

  Properties which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  
  if (!IMU.begin()) {
    Serial.println("Failed to initialize IMU!");

    while (1);
  }
  
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 
  

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  if (IMU.gyroscopeAvailable()) {
    IMU.readGyroscope(xDegree, yDegree, zDegree);
  }
  delay(1000);
}








